// screens/GlossaryScreen.tsx
import React from "react";
import { View, Text, ScrollView, Image, TouchableOpacity } from "react-native";
import Feather from "react-native-vector-icons/Feather";
import { useNavigation } from "@react-navigation/native";

export default function GlossaryScreen() {
  const navigation = useNavigation();

  return (
    <ScrollView className="flex-1 bg-background">
      <View className="bg-surface border-b border-border py-4 px-4 flex-row items-center shadow-sm mb-4">
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Feather name="x" size={24} color="#000000" />
        </TouchableOpacity>
      </View>

      <View className="px-4 mb-4">
        <Text className="text-2xl font-bold text-surfaceText">Glossary</Text>
      </View>

      <View className="px-4">
        <View className="flex-row items-center mb-4">
          <Image
            source={require("@assets/khalil.png")}
            className="w-10 h-10 rounded-full mr-3"
          />
          <View>
            <Text className="text-lg font-bold text-surfaceText">
              Khalil Zouari
            </Text>
            <Text className="text-sm text-mutedText">
              Written by Khalil Zouari
            </Text>
            <Text className="text-sm text-mutedText">
              Updated over 1 months ago
            </Text>
          </View>
        </View>

        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Annual appreciation:{" "}
          </Text>
          projected growth in the market value of the asset over 1 year
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Example: </Text>
          consider a property that is acquired at a price of{" "}
          <Text className="font-bold text-surfaceText">TDN 1,000,000</Text> with
          buying costs worth{" "}
          <Text className="font-bold text-surfaceText">TDN 100,000</Text>. The
          total investment amount is{" "}
          <Text className="font-bold text-surfaceText">TDN 1,100,000</Text>.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Capital Appreciation:{" "}
          </Text>
          Assuming the property is sold after a few years at a price of{" "}
          <Text className="font-bold text-surfaceText">TDN 1,500,000</Text> (net
          of selling costs), the capital appreciation is{" "}
          <Text className="font-bold text-surfaceText">TDN 400,000</Text>, or
          36.4% (i.e.{" "}
          <Text className="font-bold text-surfaceText">TDN 400,000</Text> /{" "}
          <Text className="font-bold text-surfaceText">TDN 1,100,000</Text>).
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Yearly Investment Return:{" "}
          </Text>
          Total ROI over 5 years (rental income/net yield + annual appreciation)
          averaged on an annual basis.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Typical ROI:{" "}
          </Text>
          Our properties usually have around a{" "}
          <Text className="font-bold text-surfaceText">50%</Text> total ROI over
          5 years, so averaging out on a yearly basis is around{" "}
          <Text className="font-bold text-surfaceText">10%</Text>.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Dividend: </Text>
          The payout an investor in an asset receives after subtracting all
          costs.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Example: </Text>
          in the case of 10 investors co-owning a property, the dividend is the
          payment each investor receives. It is the total rent generated by the
          property divided by{" "}
          <Text className="font-bold text-surfaceText">10</Text> (minus all
          costs).
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Gross Yield:{" "}
          </Text>
          projected annual percentage return that an investment generates before
          deducting expenses like management fees and maintenance costs.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Example: </Text>
          if a property is priced at{" "}
          <Text className="font-bold text-surfaceText">TDN 1,000,000</Text> and
          rented for{" "}
          <Text className="font-bold text-surfaceText">TDN 100,000</Text> per
          year, it generates a gross income of{" "}
          <Text className="font-bold text-surfaceText">TDN 100,000</Text> and a
          gross yield of <Text className="font-bold text-surfaceText">10%</Text>
          .
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Funding Target:{" "}
          </Text>
          The capital required to be raised in order to complete the purchase of
          the property.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Example: </Text>
          if a fund is looking to purchase a property at a price of{" "}
          <Text className="font-bold text-surfaceText">TDN 1,000,000</Text> and
          executing the transaction incurs costs of{" "}
          <Text className="font-bold text-surfaceText">TDN 50,000</Text>, the
          funding target will be{" "}
          <Text className="font-bold text-surfaceText">TDN 1,050,000</Text>.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            My Property Portfolio:{" "}
          </Text>
          The collection of all the property investments that you hold with
          korpor.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Note: </Text>
          Please note that korpor does not provide discretionary portfolio
          management. What does that mean for you? It means that korpor will not
          manage or make decisions on your behalf. You have all the say and
          decision-making power.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Net Yield:{" "}
          </Text>
          projected annual percentage return that an investment generates after
          all expenses are deducted.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Example: </Text>
          consider a property that is priced at{" "}
          <Text className="font-bold text-surfaceText">TDN 1,000,000</Text> and
          rented for{" "}
          <Text className="font-bold text-surfaceText">TDN 100,000</Text> per
          year, with costs of{" "}
          <Text className="font-bold text-surfaceText">TDN 25,000</Text> per
          year. The property generates a net income of{" "}
          <Text className="font-bold text-surfaceText">TDN 75,000</Text> and a
          net yield of <Text className="font-bold text-surfaceText">7.5%</Text>.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            ROI (Return on Investment):{" "}
          </Text>
          The ratio of the price differential of an asset at the end of a period
          plus all the income generated by the asset to the original price paid.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Example: </Text>a
          property purchased for price A and sold after 5 years for price B, the
          ROI is: [B-A+Rental income during the 5 years] / A.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            SPV (Special Purpose Vehicle):{" "}
          </Text>
          A company created for the purpose of executing a single transaction.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          In the case of korpor, every property will be purchased through an
          individual SPV. This streamlines the investment process by granting
          shares in the property's SPV to its shareholders.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Title Deed:{" "}
          </Text>
          An official document registered with the real estate regulator
          validating the owner(s) of a property.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">
            Transaction Costs:{" "}
          </Text>
          The additional costs incurred during the execution of a deal in
          addition to the asset purchase price.
        </Text>
        <Text className="text-lg text-surfaceText mb-4">
          <Text className="text-xl font-bold text-surfaceText">Example: </Text>
          purchasing investment property requires paying transfer fees,
          registration fees, and additional charges like valuation and KYC fees.
        </Text>
      </View>
    </ScrollView>
  );
}
